### ISSUE TITLE
highlight sometimes too close to text when using "Dynamic highlights" plugin

### ISSUE THREAD

**Issue by danieltomasz** [whereiswhere/iB-Writer#1]
Hi, nice theme!
I am using the "Dynamic highlight plugin" (it highlights all occurrences of word under cursor or the one highlighted by user) and I noticed that with this theme the highlight is sometimes too close to the text (  which occurences are highlighted differently depends from the placing current highlight)
![image](https://user-images.githubusercontent.com/7980381/235308174-e0d151d1-e65f-4a5f-9849-67fb93698ea9.png)
![image](https://user-images.githubusercontent.com/7980381/235308260-a7784d2b-cb46-48ea-9f72-09b962055cdb.png)

When using other themes the effect is not so visible, probably because this theme is using a thicker highlight "_ _ _ "

Dynamic highlights is using the following css https://github.com/nothingislost/obsidian-dynamic-highlights/blob/master/styles.css
```
/* #region selection highlighter styles */

.cm-matched-word,
.cm-matched-string {
  text-decoration: underline dashed var(--text-accent);
}

.cm-current-word,
.cm-current-string {
  text-decoration: underline dotted var(--text-accent);
}
```
The issue  might be solved by the creator of the plugin (but plugin stoped with updates a year ago) but I wonder if this theme might also fix this by moving the "_ _ _" highlights a few pixels/points  more below word?

I could understand if this is not fixed, as my use case is not that common :)

**Comment by whereiswhere** [comment]
I think it can't be done by editing the theme, I could add a new underline highlight a few pixels more below but the plugin's own highlight is still there.

I checked that it seems other themes (including Default theme) also behave like that. So I think it needs to be solved by tweak the plugin itself.

**Comment by danieltomasz** [comment]
Thanks for looking into it!

Indeed , I think it might be related to how vanilla Obsidian made computation for applying CSS, this effect is visible only below certain magnitude of zoom, and it might depends also from the screen resolution of the person who is checking it.

In my case I was getting different behaviour with default theme and your theme, and it might be related to the level of zoom and my screen resolution (as those might influence how the css rules are applied)

I am closing this issue as I dont see that something can be directly done now and the issue is rather a curiosity than an critical issue.
