### ISSUE TITLE
[Bug] Notes in canvas - problem with text  in the notes

### ISSUE THREAD

**Issue by danieltomasz** [whereiswhere/iB-Writer#2]
Just find this bug - this time in sandboxed vault, only BRAT 42 and this theme is installed, I am  using Obsidian 1.2.6.
The text in newly created card the text not appear until I resize the note
the first note  is just after creation, the second contains the  same text, but it  is resized to make text visible
![image](https://user-images.githubusercontent.com/7980381/235317255-39f500d7-299f-4c45-b932-393768c1dcee.png)

the text in existing notes in canvas is also hidden when this theme is used

**Comment by whereiswhere** [comment]
This bug should be fixed by now.

The theme is still waiting for review by Obsidian, so you may have to re-install manually.
